name: metzudat_halikud
repository: https://github.com/ofekgrim/likud_news

packages:
  - apps/mobile
  - packages/**

ide:
  intellij:
    enabled: true

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: dart analyze --fatal-infos
    exec:
      concurrency: 1
    description: Run dart analyze in all packages

  test:
    run: flutter test --coverage
    packageFilters:
      flutter: true
    description: Run tests in all Flutter packages

  codegen:
    run: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
    description: Run build_runner in all packages that depend on it

  format:
    run: dart format .
    description: Format all Dart files

  clean:
    run: flutter clean
    packageFilters:
      flutter: true
    description: Clean all Flutter packages
